# -*- coding: utf-8 -*-
"""displayimages

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKBkVTncxdVbLnaG67o_XPOcvmLUbRwA
"""

import matplotlib.pyplot as plt
import numpy as np
import torch
import torchvision

# functions to show an image


def imshow(img):
    img = img / 2 + 0.5     # unnormalize
    npimg = img.numpy()
    plt.imshow(np.transpose(npimg, (1, 2, 0)))


def show_random_image(dataset, classes):

	# get some random training images
	dataiter = iter(dataset)
	images, labels = dataiter.next()

	img_list = range(5, 10)

	# show images
	print('shape:', images.shape)
	imshow(torchvision.utils.make_grid(images[img_list]))
	# print labels
	print(' '.join('%5s' % classes[labels[j]] for j in img_list))